// Code generated by protoc-gen-go.
// source: proto/gcm.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	proto/gcm.proto

It has these top-level messages:
	Action
	Client
	ClientList
	RegisterNewClient
	BroadcastNewClient
	SendClientList
	PingClient
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = math.Inf

type Action_Name int32

const (
	Action_UNSPECIFIED          Action_Name = 0
	Action_REGISTER_NEW_CLIENT  Action_Name = 1
	Action_BROADCAST_NEW_CLIENT Action_Name = 2
	Action_SEND_CLIENT_LIST     Action_Name = 3
	Action_PING_CLIENT          Action_Name = 4
)

var Action_Name_name = map[int32]string{
	0: "UNSPECIFIED",
	1: "REGISTER_NEW_CLIENT",
	2: "BROADCAST_NEW_CLIENT",
	3: "SEND_CLIENT_LIST",
	4: "PING_CLIENT",
}
var Action_Name_value = map[string]int32{
	"UNSPECIFIED":          0,
	"REGISTER_NEW_CLIENT":  1,
	"BROADCAST_NEW_CLIENT": 2,
	"SEND_CLIENT_LIST":     3,
	"PING_CLIENT":          4,
}

func (x Action_Name) Enum() *Action_Name {
	p := new(Action_Name)
	*p = x
	return p
}
func (x Action_Name) String() string {
	return proto1.EnumName(Action_Name_name, int32(x))
}
func (x *Action_Name) UnmarshalJSON(data []byte) error {
	value, err := proto1.UnmarshalJSONEnum(Action_Name_value, data, "Action_Name")
	if err != nil {
		return err
	}
	*x = Action_Name(value)
	return nil
}

// This could be a bit redundant, giving that the type of message already
// identifies the action.
type Action struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Action) Reset()         { *m = Action{} }
func (m *Action) String() string { return proto1.CompactTextString(m) }
func (*Action) ProtoMessage()    {}

// A connected client
type Client struct {
	Name              *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	RegistrationToken *string `protobuf:"bytes,2,req,name=registration_token" json:"registration_token,omitempty"`
	ProfilePictureUrl *string `protobuf:"bytes,3,req,name=profile_picture_url" json:"profile_picture_url,omitempty"`
	XXX_unrecognized  []byte  `json:"-"`
}

func (m *Client) Reset()         { *m = Client{} }
func (m *Client) String() string { return proto1.CompactTextString(m) }
func (*Client) ProtoMessage()    {}

func (m *Client) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Client) GetRegistrationToken() string {
	if m != nil && m.RegistrationToken != nil {
		return *m.RegistrationToken
	}
	return ""
}

func (m *Client) GetProfilePictureUrl() string {
	if m != nil && m.ProfilePictureUrl != nil {
		return *m.ProfilePictureUrl
	}
	return ""
}

// A list of clients
type ClientList struct {
	Clients          []*Client `protobuf:"bytes,1,rep,name=clients" json:"clients,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *ClientList) Reset()         { *m = ClientList{} }
func (m *ClientList) String() string { return proto1.CompactTextString(m) }
func (*ClientList) ProtoMessage()    {}

func (m *ClientList) GetClients() []*Client {
	if m != nil {
		return m.Clients
	}
	return nil
}

// Registration request for a new client (device -> server)
type RegisterNewClient struct {
	Client           *Client `protobuf:"bytes,1,req,name=client" json:"client,omitempty"`
	Action           *Action `protobuf:"bytes,2,req,name=action" json:"action,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RegisterNewClient) Reset()         { *m = RegisterNewClient{} }
func (m *RegisterNewClient) String() string { return proto1.CompactTextString(m) }
func (*RegisterNewClient) ProtoMessage()    {}

func (m *RegisterNewClient) GetClient() *Client {
	if m != nil {
		return m.Client
	}
	return nil
}

func (m *RegisterNewClient) GetAction() *Action {
	if m != nil {
		return m.Action
	}
	return nil
}

// Broadcast new client to registered clients
type BroadcastNewClient struct {
	Client           *Client `protobuf:"bytes,1,req,name=client" json:"client,omitempty"`
	Action           *Action `protobuf:"bytes,2,req,name=action" json:"action,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *BroadcastNewClient) Reset()         { *m = BroadcastNewClient{} }
func (m *BroadcastNewClient) String() string { return proto1.CompactTextString(m) }
func (*BroadcastNewClient) ProtoMessage()    {}

func (m *BroadcastNewClient) GetClient() *Client {
	if m != nil {
		return m.Client
	}
	return nil
}

func (m *BroadcastNewClient) GetAction() *Action {
	if m != nil {
		return m.Action
	}
	return nil
}

// Send registered clients list to new client
type SendClientList struct {
	ClientList       *ClientList `protobuf:"bytes,1,req,name=clientList" json:"clientList,omitempty"`
	Action           *Action     `protobuf:"bytes,2,req,name=action" json:"action,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *SendClientList) Reset()         { *m = SendClientList{} }
func (m *SendClientList) String() string { return proto1.CompactTextString(m) }
func (*SendClientList) ProtoMessage()    {}

func (m *SendClientList) GetClientList() *ClientList {
	if m != nil {
		return m.ClientList
	}
	return nil
}

func (m *SendClientList) GetAction() *Action {
	if m != nil {
		return m.Action
	}
	return nil
}

// Ping client
type PingClient struct {
	To               *Client `protobuf:"bytes,1,req,name=to" json:"to,omitempty"`
	From             *Client `protobuf:"bytes,2,req,name=from" json:"from,omitempty"`
	Action           *Action `protobuf:"bytes,3,req,name=action" json:"action,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PingClient) Reset()         { *m = PingClient{} }
func (m *PingClient) String() string { return proto1.CompactTextString(m) }
func (*PingClient) ProtoMessage()    {}

func (m *PingClient) GetTo() *Client {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *PingClient) GetFrom() *Client {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *PingClient) GetAction() *Action {
	if m != nil {
		return m.Action
	}
	return nil
}

func init() {
	proto1.RegisterEnum("proto.Action_Name", Action_Name_name, Action_Name_value)
}
